In [9]:
import pandas as pd

client_train_data = pd.read_csv("data/client_train.csv")
invoice_train_data = pd.read_csv("data/invoice_train.csv")

C:\Users\tapio\AppData\Local\Temp\ipykernel_35368\521758544.py:4: DtypeWarning: Columns (0: counter_statue) have mixed types. Specify dtype option on import or set low_memory=False.
  invoice_train_data = pd.read_csv("data/invoice_train.csv")

disrict            int64
client_id            str
client_catg        int64
region             int64
creation_date        str
target           float64
dtype: object

In [15]:
client_train_data.head()

   disrict          client_id  client_catg  region creation_date  target
0       60     train_Client_0           11     101    31/12/1994     0.0
1       69     train_Client_1           11     107    29/05/2002     0.0
2       62    train_Client_10           11     301    13/03/1986     0.0
3       69   train_Client_100           11     105    11/07/1996     0.0
4       62  train_Client_1000           11     303    14/10/2014     0.0

In [ ]:
x = client_train_data.loc[
    (client_train_data["target"] > 0.0) & (client_train_data["target"] < 1.0)
]
print(x)

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [16]:
invoice_train_data.head()

,client_id,invoice_date,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
0,train_Client_0,2014-03-24,11,1335667,0,203,8,1,82,0,0,0,14302,14384,4,ELEC
1,train_Client_0,2013-03-29,11,1335667,0,203,6,1,1200,184,0,0,12294,13678,4,ELEC
2,train_Client_0,2015-03-23,11,1335667,0,203,8,1,123,0,0,0,14624,14747,4,ELEC
3,train_Client_0,2015-07-13,11,1335667,0,207,8,1,102,0,0,0,14747,14849,4,ELEC
4,train_Client_0,2016-11-17,11,1335667,0,207,9,1,572,0,0,0,15066,15638,12,ELEC